language: generic
sudo: required

services:
    - docker

before_install:
    - docker build -t tshah1900/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true tshah1900/docker-react npm run test -- --coverage
 
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-138903241193"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY