# Use existing docker image as a base
# hub.docker.com where you look for node
FROM node:alpine

WORKDIR '/app'

# Download and install dependency
# copy files from current dir to container
COPY package.json .
RUN npm install
COPY . .

# Tell the image what to do when it starts as a container
CMD ["npm", "run", "start"]